# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multivariate FAR estimation (C++)
#'
#' This function estimates the functional coefficients of a multivariate FAR model at specific reference signal value u0.
#'
#' @param y A matrix containing the multivariate time series data
#' @param u A vector containing the reference signal series
#' @param u0 Specific value of reference signal for local approximation
#' @param p The order of FAR(p) model
#' @param d The lag of the reference signal
#' @param bwp The bandwidth proportion from 0 to 1 (with respect to the range of observations)
#' @return A matrix of slope and intercept estimates (locally at u0).
#' @keywords internal
FARest <- function(y, u, u0, p, d, bwp) {
    .Call('_mxfar_FARest', PACKAGE = 'mxfar', y, u, u0, p, d, bwp)
}


#' Multivariate MXFAR estimation (C++)
#'
#' This function estimates the functional coefficients of a multivariate mixed-effects FAR model at specific reference signal value u0.
#'
#' @param SeriesNum A numeric vector stating the number of series in a 'group' data
#' @param Tlength A numeric scalar stating the number of time points per series
#' @param y A matrix containing the 'stacked' multivariate time series data from multiple series
#' @param u A vector containing the 'stacked' reference signal series
#' @param u0 Specific value of reference signal for local approximation
#' @param p The order of MXFAR(p) model
#' @param d The lag of the reference signal
#' @param bwp The bandwidth proportion from 0 to 1 (with respect to the range of observations)
#' @return A matrix of slope and intercept estimates (locally at u0).
#' @keywords internal
MXFARest <- function(SeriesNum, Tlength, y, u, u0, p, d, bwp) {
    .Call('_mxfar_MXFARest', PACKAGE = 'mxfar', SeriesNum, Tlength, y, u, u0, p, d, bwp)
}

